### ISSUE TITLE
macOS SITL build broken

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#13120]
After a fresh brew and brew dependencies install, I can't build for Gazebo SITL anymore.

```
[13/92] Generating /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf
FAILED: /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf
cd /Users/julianoes/src/Firmware/Tools/sitl_gazebo && rm -f /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf && /usr/local/opt/python/libexec/bin/python /Users/julianoes/src/Firmware/Tools/sitl_gazebo/scripts/xacro.py -o /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.xacro enable_mavlink_interface:=true enable_ground_truth:=false enable_wind:=false enable_logging:=false rotors_description_dir:=/Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description send_vision_estimation:=true send_odometry:=false && gz sdf -p /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf >> /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf && rm -f /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf

dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.20.dylib
  Referenced from: /usr/local/bin/gz
  Reason: image not found
/bin/sh: line 1:  7162 Abort trap: 6           gz sdf -p /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/rotors_description/urdf/iris_base.urdf >> /Users/julianoes/src/Firmware/Tools/sitl_gazebo/models/iris/iris.sdf
```

**Comment by julianoes** [comment]
It looks like we need to wait for https://github.com/osrf/homebrew-simulation/issues/850.

**Comment by TSC21** [comment]
Yep I was struggling with the same this weekend on sitl_gazebo: https://travis-ci.org/PX4/sitl_gazebo/jobs/594207021

**Comment by julianoes** [comment]
brew on macOS is like being on a rolling release Linux :cry:, it doesn't make it easy.

**Comment by TSC21** [comment]
Solution should come with https://github.com/osrf/homebrew-simulation/pull/849

**Comment by julianoes** [comment]
Great, this is fixed. Now I can continue to debug gstreamer and glib dependency issues.

**Comment by TSC21** [comment]
@julianoes I am already working on that here if you want to check: https://github.com/PX4/sitl_gazebo/pull/353 It reaches the build stage but still fails because if the problem above.
