### ISSUE TITLE
sdlog issues

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#4080]
- OUT1 logged with OUT0 values
- strange uint8 values

![image](https://cloud.githubusercontent.com/assets/14801663/14055189/000219b6-f2e0-11e5-8494-715ffdeb037c.png)

**Comment by sanderux** [comment]
Also, logging in SITL no longer works.
Reverting this commit: https://github.com/PX4/Firmware/commit/2dcd529ad873555a9a67002509f0530c6fb01c76 brought back SITL logging. Not tested for actual flight log problems yet.

@LorenzMeier

**Comment by bo-rc** [comment]
#4087 seems to fix the SITL bug.

**Comment by LorenzMeier** [comment]
@sanderux It all looks correct code-wise. Are you sure this is happening on master?

**Comment by sanderux** [comment]
Might have been related to the double locking. I got a user report i'll check

**Comment by LorenzMeier** [comment]
I'm closing this meanwhile. Please re-open if its a real issue on master.

**Comment by sanderux** [comment]
At least ion sitl;
- actuators out0 and out1 are identical
- uint8 values remain 0 (at least the ones i tested)

![image](https://cloud.githubusercontent.com/assets/14801663/14141728/2771d618-f681-11e5-8155-bf049bb1f92c.png)

**Comment by sanderux** [comment]
On latest master the uint8 values get random spikes:
![image](https://cloud.githubusercontent.com/assets/14801663/14141952/d36b4e08-f682-11e5-8304-2f070cd8b1bb.png)

**Comment by sanderux** [comment]
@LorenzMeier would be very nice to have this fixed before i go out test flying this weekend

**Comment by LorenzMeier** [comment]
Can you share the exact steps in SITL to repro for me?

**Comment by sanderux** [comment]
```
git checkout master
make posix_sitl_default gazebo_standard_vtol
```
fly mission
ctrl-c after LANDING DETECTED
open log from ~/src/Firmware/build_posix_sitl_default/src/firmware/posix/rootfs/fs/microsd/log/2016-03-30 in flightplot
add out0 group and out1 group

**Comment by LorenzMeier** [comment]
Fixed by #4124.

**Comment by sanderux** [comment]
uint8 issues remain
![image](https://cloud.githubusercontent.com/assets/14801663/14228288/caa500a8-f910-11e5-8907-dcd7c90b17b4.png)

**Comment by LorenzMeier** [comment]
@sanderux Just fixed it. Please check.
