### ISSUE TITLE
Yaw/thrust saturation and loss of control during flight

### ISSUE THREAD

**Issue by bresch** [PX4/Firmware#7288]
Hi everyone,

During a position control flight with my VTOL (in MC mode only), I encountered a really strange behavior. After flying perfectly well, the yaw control was suddenly lost and the drone was loosing altitude.

![esc_response2](https://cloud.githubusercontent.com/assets/14822839/26549616/2bc1ae62-447a-11e7-81eb-4d79c5c93205.png)

As you can see, around t=59s, the drone did not respond to the yaw command even if the ESC reported acceleration and deceleration of the motors. After that between t=63s and t=69s, the drone is spinning around it's yaw axis and since it was loosing altitude, the thrust did reach saturation, without any RPM response.

I'm suspecting a mixer saturation or an ESC issue. 

Link to the complete [log](http://logs.px4.io/plot_app?log=55960095-7efd-4e28-8acc-1854828e75bc).

Finally, my setup is a PixHawk Pro with Orel 20 ESCs and a mRo GPS.

**Comment by bresch** [comment]
New log from this morning, same issue after less than 3 minutes. 
Same sequence: 
1. No yaw response to the motors ramping up and down (t=[167,170]s)
2. Altitude loss 
3. Thrust saturation 
4. No more yaw control

![yaw_control](https://cloud.githubusercontent.com/assets/14822839/26550234/ff224c10-447c-11e7-9d99-c80f70324bd3.png)
[FlightReview link](http://logs.px4.io/plot_app?log=28ee3ee8-5a91-448e-853e-bcf058a70986)

**Comment by bresch** [comment]
I maybe found the issue in the `mixer_multirotor.cpp` file ([link](https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#L326-L337)).
```
} else if (out > 1.0f) {
			// allow to reduce thrust to get some yaw response
			float prop_reduction = fminf(0.15f, out - 1.0f);
			// keep the maximum requested reduction
			thrust_reduction = fmaxf(thrust_reduction, prop_reduction);

			if (fabsf(_rotors[i].yaw_scale) <= FLT_EPSILON) {
				yaw = 0.0f;

			} else {
				yaw = (1.0f - ((roll * _rotors[i].roll_scale + pitch * _rotors[i].pitch_scale) *
					       roll_pitch_scale + thrust + boost)) / _rotors[i].yaw_scale;
}
```
When the output saturates, the `thrust_reduction` is computed but the new yaw value is then computed again with the old unreduced thrust. The final result is then a reduced thrust with no yaw control.

**Comment by bresch** [comment]
I fixed the computation of the new yaw value with the modified thrust and flew three times like a crazy pilot to reach the saturations and now it's fine. I'll do a PR for the fix.
You can see the logs [here](http://logs.px4.io/plot_app?log=08e124ec-c9d0-4205-a740-9e48006290d9), [here](http://logs.px4.io/plot_app?log=4105252f-3d0b-48a7-9190-93a3e0cc8769) and [here](http://logs.px4.io/plot_app?log=c3a2cb92-66c6-40fd-8a95-8c560f8ac490)

**Comment by Stifael** [comment]
@bresch: 
what I still don't get why the velocity setpoint is at zero for both vx and vy despite the fact that the vehicle is in position control using just velocity control loop:
![tracking_failure](https://cloud.githubusercontent.com/assets/13449161/26574092/5f9d1c5c-4520-11e7-9d2a-a7b439ec6d1d.png)

**Comment by Stifael** [comment]
and once you switch the mode, everything is fine. seems like there is another issue independent of the mixture...

**Comment by bresch** [comment]
@Stifael Could you explain a bit more the issue you are pointing out please? I don't get it. And from which log is your plot?

**Comment by Stifael** [comment]
@bresch: it is from the log that you posted. 
why did you assume from the beginning that just the yaw control was lost?

**Comment by bresch** [comment]
@Stifael You are right. I found that it coincides with the value of the x-y RC stick going to the central position. Do you think it is related?
![vy_tracking](https://cloud.githubusercontent.com/assets/14822839/26584361/ce79e16e-4548-11e7-9b8e-3170bb4d41f4.png)
(The RC value not shown is at 0)

**Comment by mhkabir** [comment]
If the sticks are at zero, shouldn't the vel sp still have some value because it's trying to hold position against external disturbances?

**Comment by Stifael** [comment]
not necessarily. if the vehicle has not entered position control, then the velocity setpoint will be zero. The vehicle enters position control only if the stick are close to zero and the velocity is low

**Comment by Stifael** [comment]
so the param that defines the threshold for entering position control is MPC_HOLD_MAX_XY, which is set to 0.8. But the velocity in y is ~3m/s, so the vehicle should not have entered position control and therefore is completely fine to have a velocity setpoint of 0. Nonetheless, still strange to have such a bad tracking right it setpoint goes to zero

**Comment by bresch** [comment]
The position tracing was really bad in this log because I had a misalignment of the mag heading and the frame heading. The correction was then projected into a slightly rotated frame which causes a "circling around position" error. The issue isn't on the control side.
