### ISSUE TITLE
Error compiling v1.7.0-rc1 for eagle_default target

### ISSUE THREAD

**Issue by r0gelion** [PX4/Firmware#8297]
I'm using Ubuntu 14.04LTS

1. I tried to compile v1.7.0-rc1:
`make eagle_default`
2. Got the error: http://pasted.co/0a7d6f31
2.1. This error recommends running the next command:
`sudo apt-get install python-toml python-numpy`
2.2. I ran the previous command but I received the error that python-toml package wasn't located.

I follow the next steps to to solve the issue:
1. Downloaded the python-toml deb file from [here](https://packages.ubuntu.com/xenial/all/python-toml/download)
2. Installed the deb package using Ubuntu's package installer.
3. Ran the next command again:
`sudo apt-get install python-toml python-numpy`
After the above step I was able to compile

@jlecoeur @dagar

**Comment by sparky002** [comment]
I ran into the same problem compiling v1.7.0-rc1 for px4fmu-v2_default and px4fmu-v3_default on ubuntu 14.04lts. Same solution worked on my end.

**Comment by huangwen0907** [comment]
@r0gelion 
>   sudo -H pip install pyserial empy toml pandas jinja2
Maybe can fix you problem.

**Comment by r0gelion** [comment]
@huangwen0907 Thank you, the problem was solved with the process shown at the issue description.
 
@jlecoeur should we keep this issue open?

**Comment by anandbaskaran** [comment]
I am still getting this same error. I tried installing with both pip and with apt-get and it installed properly. But, whenever I run the make of PX4 I get the same error.

**Comment by hamishwillee** [comment]
@anandbaskaran Best not to hijack issues that have been closed some time ago. Create a new one describing the environment you used and the precise problem.
