### ISSUE TITLE
V1.7.2 HITL failed

### ISSUE THREAD

**Issue by ZingHD** [PX4/Firmware#8522]
**Bug Report** 
The firmware upgrade to v1.7.2, the hardware in the loop simulation, the sensor will prompt detection failed, the simulation will be flight fault
![qq 20171223141023](https://user-images.githubusercontent.com/17960473/34317503-587ca046-e7eb-11e7-8156-ce5921e575cf.png)

![default](https://user-images.githubusercontent.com/17960473/34330879-94aff398-e95c-11e7-9133-90568103cdda.png)

**Comment by dagar** [comment]
What's your setup? Is this jmavsim? When was it last working?

**Comment by TSC21** [comment]
@arwagoner probably you are facing this same problem with Gazebo ATM, which means the problem may be coming from the Firmware side. Can you expose here your findings while integrating the HIL functionality for Gazebo? Thanks

**Comment by ZingHD** [comment]
@dagar  The firmware 1.6.5 HITL is work，I can easily debug parameters。

**Comment by LorenzMeier** [comment]
@ZingHD I've fixed this here: https://github.com/PX4/Firmware/pull/8532

**Comment by ZingHD** [comment]
@LorenzMeier  I had change the three files but it not fixed
src/modules/commander/state_machine_helper.cpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/commander/commander.cpp

**Comment by LorenzMeier** [comment]
It definitely is. If it didn't work for you then either the changes were not consistent or you didn't configure the system correctly.

**Comment by LorenzMeier** [comment]
Also note the documentation here:
https://dev.px4.io/en/simulation/hitl.html

**Comment by LorenzMeier** [comment]
I've found one caveat - if you launch QGC after jMAVSim the initial launch can eat all of the CPU and the simulation diverges.

**Comment by arwagoner** [comment]
These changes worked for HIL in Gazebo. Thanks! 
![gazebo_hitl](https://user-images.githubusercontent.com/3769314/34416002-62e86362-ebbf-11e7-8cae-2e60b3bec887.gif)

**Comment by ZingHD** [comment]
@LorenzMeier  It works on Gazebo SITL thank you very much. @arwagoner I can only found the document
https://dev.px4.io/en/simulation/gazebo.html use Gazebo SITL,can you tell me how to use Gazebo HITL，I  well use HITL ，I want to test a week to determine the stability of the flight control，thanks。

**Comment by arwagoner** [comment]
@ZingHD Gazebo HITL has not been merged yet https://github.com/PX4/sitl_gazebo/pull/146. The docs will be updated shortly with instructions on how to use it.

**Comment by ZingHD** [comment]
@arwagoner Thank you answer.
